models/Post.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * @property int id
 * @property int user_id
 * @property string title
 * @property string excerpt
 * @property string content
 * @property string img
 * @property string created_at
 */

class Post extends ActiveRecord
{
//    public $img;
    public static function tableName()
    {
        return 'posts';
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['title', 'content', 'img'], 'required'],
        ];
    }

}

controllers/PostController.php
<?php

namespace app\controllers;

use app\models\Post;
use app\models\PublishForm;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\UploadedFile;

class PostController extends Controller
{

    public function actionIndex()
    {
        $query = Post::find()->with('user');
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 4, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $posts = $query->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('index', compact('posts', 'pages'));
    }

    public function actionView($id)
    {
        $query = Post::find()->where(['id' => $id]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 4, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $posts = $query->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('post', compact('posts'));
    }

    public function actionUpdate($id)
    {
        $model = Post::findOne($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            return $this->redirect('index');
        }
        return $this->render('edit', ['model' => $model]);
    }

    public function actionPost()
    {
        $model = new PublishForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->img = UploadedFile::getInstance($model, 'img');
            $way = $model->upload();
            if ($post = $model->publish($way)) {
                return $this->redirect('index');
            }
        }
        return $this->render('publish', ['model' => $model]);
    }

}

views/post/edit.php
<?php

use yii\bootstrap5\ActiveForm;
use yii\helpers\Html;

$form = ActiveForm::begin(['layout' => 'horizontal']); ?>
<?= $form->field($model, 'title') ?>
<?= $form->field($model, 'content')->textarea(['rows' => 5]) ?>
<?= $form->field($model, 'img') ?>
    <div class="form-group">
        <div class="offset-lg-5 col-lg-7">
            <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>
<?php ActiveForm::end(); ?>

views/post/index.php
<?php

/** @var yii\web\View $this */

$this->title = Yii::$app->name;
?>

<section class="bg-text-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="bg-text">
                    <h3>Classic BLOG Design</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                        voluptate velit esse cillum dolore eu fugiat nulla </p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="blog-post-area">
    <div class="container">
        <div class="row">
            <div class="blog-post-area-style">
                <!--                <div class="col-md-12">-->
                <!--                    <div class="single-post-big">-->
                <!--                        <div class="big-image">-->
                <!--                            <img src="img/post-image1.jpg" alt="">-->
                <!--                        </div>-->
                <!--                        <div class="big-text">-->
                <!--                            <h3><a href="#">Post Title Goes Here.</a></h3>-->
                <!--                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>-->
                <!--                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>-->
                <!--                            <h4><span class="date">25 February 2017</span><span class="author">Posted By: <span class="author-name">Kabbo Liate</span></span>-->
                <!--                            </h4>-->
                <!--                        </div>-->
                <!--                    </div>-->
                <!--                </div>-->
                <?php foreach ($posts as $post): ?>
                    <div class="col-md-3">
                        <div class="single-post">
                            <?= \yii\helpers\Html::img("@web/{$post->img}") ?>
                            <h3>
                                <a href="<?= \yii\helpers\Url::to(['post/view', 'id' => $post->id]) ?>"><?= $post->title ?></a>
                            </h3>
                            <h4><span>Posted By: <span class="author-name">
<!--                                    <a href="--><?php //= \yii\helpers\Url::to(['user/view', 'first_name' => $post->user->first_name]) ?><!--">-->
                                        <?= $post->user->first_name ?> <?= $post->user->last_name ?>
<!--                                    </a>-->
                                </span></span>
                            </h4>
                            <p>
                                <?= $post->excerpt ?>
                            </p>
                            <h4><span><?= Yii::$app->formatter->asDate($post->created_at, 'php:d.m.Y') ?></span></h4>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="pegination">
        <div class="nav-links">
            <?= \yii\widgets\LinkPager::widget([
                'pagination' => $pages,
            ]) ?>
        </div>
    </div>
</section>

views/post/post.php
<?php

/** @var yii\web\View $this */

$this->title = Yii::$app->name;
?>

<section class="bg-text-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="bg-text">
                    <h3>Classic BLOG Design</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                        voluptate velit esse cillum dolore eu fugiat nulla </p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="blog-post-area">
    <div class="container">
        <div class="row">
            <div class="blog-post-area-style">
                <?php foreach ($posts as $post): ?>
                    <div class="col-md-3">
                        <div class="single-post">
                            <?= \yii\helpers\Html::img("@web/{$post->img}") ?>
                            <h3>
                                <a href="<?= \yii\helpers\Url::to(['post/view', 'id' => $post->id]) ?>"><?= $post->title ?></a>
                            </h3>
                            <h4><span>Posted By: <span class="author-name">
                                    <a href="<?= \yii\helpers\Url::to(['user/view', 'first_name' => $post->user->first_name]) ?>">
                                        <?= $post->user->first_name ?> <?= $post->user->last_name ?>
                                    </a>
                                </span></span>
                            </h4>
                            <p>
                                <?= $post->content ?>
                            </p>
                            <h4><span><?= Yii::$app->formatter->asDate($post->created_at, 'php:d.m.Y') ?></span></h4>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</section>

views/post/publish.php
<?php
//
///** @var yii\web\View $this */
///** @var yii\bootstrap5\ActiveForm $form */
//
///** @var app\models\PublishForm $model */
//
//use yii\bootstrap5\ActiveForm;
//use yii\bootstrap5\Html;
//
//$this->title = 'Publish';
//$this->params['breadcrumbs'][] = $this->title;
//?>
<!--<div class="site-login">-->
<!--    <h1>--><?php //= Html::encode($this->title) ?><!--</h1>-->
<!--    <p>Please fill out the following fields to publish:</p>-->
<!--    <div class="row">-->
<!--        <div class="col-lg-5">-->
<!--            --><?php //$form = ActiveForm::begin([
//                'id' => 'login-form',
//                'fieldConfig' => [
//                    'template' => "{label}\n{input}\n{error}",
//                    'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
//                    'inputOptions' => ['class' => 'col-lg-3 form-control'],
//                    'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
//                ],
//            ]); ?>
<!---->
<!--            --><?php //= $form->field($model, 'title')->textInput(['autofocus' => true]) ?>
<!--            --><?php //= $form->field($model, 'content')->textarea(['rows' => 5]) ?>
<!--            --><?php //= $form->field($model, 'img') ?>
<!--            <div class="form-group">-->
<!--                <div class="offset-lg-1 col-lg-11">-->
<!--                    --><?php //= Html::submitButton('Publish', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
<!--                </div>-->
<!--            </div>-->
<!---->
<!--            --><?php //ActiveForm::end(); ?>
<!--        </div>-->
<!--    </div>-->
<!--</div>-->


<?php

use yii\bootstrap5\ActiveForm;
use yii\helpers\Html;

$form = ActiveForm::begin(['layout' => 'horizontal']); ?>
<?php //$form = ActiveForm::begin([
//    'id' => 'login-form',
//    'options' => ['class' => 'form-vertical'],
//]); ?>
<?= $form->field($model, 'title') ?>
<?= $form->field($model, 'content')->textarea(['rows' => 9]) ?>
<?php //= $form->field($model, 'excerpt')->textarea(['rows' => 9]) ?>
<?= $form->field($model, 'img')->fileInput() ?>
<div class="form-group">
    <div class="offset-lg-5 col-lg-7">
        <?= Html::submitButton('Publish', ['class' => 'btn btn-primary']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>
<!--</div>-->
<!--</div>-->

views/post/view.php
<?php

//global $model;

use yii\widgets\DetailView;

echo DetailView::widget([
    'model' => $model,
    'attributes' => [
        'id',
        'user_id',
        'title',
        'content',
        'img',
        'created_at'
    ],
]);